name: test

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Classes
        run: ./gradlew classes
      - name: Assemble
        run: ./gradlew assemble
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Report JUnit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: ☕ JUnit Results
          path: "**/build/test-results/**/TEST-*.xml"
          reporter: java-junit
      - name: Upload JUnit Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ☕ JUnit Results
          path: "**/build/test-results/**/TEST-*.xml"
